name: UltraLS
version: '${version}'
main: me.trouper.ultrals.UltraLS
api-version: 1.19
authors: [ TheTrouper ]
description: The only acceptable dupe plugin.
website: https://thetrouper.github.io/
permissions:
  ultrals.admin:
    default: op
    description: Access to give and take hearts from players
  ultrals.deposit:
    default: op
    description: access to the command to place hearts from bar into bank
  ultrals.withdraw:
    default: op
    description: allows withdrawing hearts to bar or item
  ultrals.revive:
    default: op
    description: allows player to revive for a cost
  ultrals.giveheart:
    default: op
    description: allows player to transfer hearts
  ultrals.bal:
    default: op
    description: Allow viewing of balance
commands:
  ultrals:
    description: Admin command to edit people's hearts
    usage: /ultrals
    permission: ultrals.admin
    aliases:
      - lsadmin
      - adminls
      - ls
      - uls
  deposit:
    description: put hearts from you healthbar into your bank
    permission: ultrals.deposit
    usage: /deposit <int>
  withdraw:
    description: put hearts from you bank into your health bar or inventory
    permission: ultrals.withdraw
    usage: /withdraw <int> [bank|item]
  giveheart:
    description: Give hearts to players
    permission: ultrals.giveheart
    usage: /giveheart <player> <int> [from your; bank|bar] [to their; bank|bar]
    aliases:
      - gh
      - givelife
      - gl
  revive:
    description: Revive a player for the cost of a player death
    permission: ultrals.revive
    usage: /revive <dead player>
  bank:
    description: View your balance
    permission: ultrals.bal
    usage: /bank
